spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_db_name
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
#  security:
#    user:
#      name: admin
#      password: 123123
server:
  servlet:
    context-path: /admin
